# Generated by Django 5.1.2 on 2024-12-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.UUIDField()),
                ('player_name', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('opponent', models.CharField(max_length=200)),
                ('game_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(max_length=100)),
                ('line_value', models.FloatField()),
                ('over_multiplier', models.FloatField()),
                ('under_multiplier', models.FloatField()),
                ('bet365_odds', models.JSONField()),
                ('kambi_odds', models.JSONField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.playerdetails')),
            ],
        ),
    ]
