# Generated by Django 5.1.2 on 2024-12-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='player',
        ),
        migrations.DeleteModel(
            name='PlayerDetails',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
