# Generated by Django 5.1.2 on 2024-12-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerdetails',
            unique_together={('player_id', 'game_date_time')},
        ),
    ]
