# Generated by Django 5.1.2 on 2024-12-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_alter_playerdetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerdetails',
            unique_together={('player_name', 'game_date_time')},
        ),
    ]
