# Generated by Django 5.1.2 on 2024-12-24 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0005_alter_playerdetails_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetails',
            name='player_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
