# Generated by Django 5.1.2 on 2024-12-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0006_alter_playerdetails_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='bet365_odds',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stat',
            name='kambi_odds',
            field=models.JSONField(default=dict),
        ),
    ]
