# Generated by Django 5.1.2 on 2024-12-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0007_alter_stat_bet365_odds_alter_stat_kambi_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='over_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='under_multiplier',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
