# Generated by Django 5.1.2 on 2024-12-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0008_alter_stat_over_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsbookOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportsbook_name', models.CharField(max_length=100)),
                ('american_odds', models.CharField(max_length=100)),
                ('over_under', models.CharField(blank=True, max_length=10, null=True)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='soccer.stat')),
            ],
        ),
    ]
