# Generated by Django 5.1.2 on 2024-12-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0009_sportsbookodds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='bet365_odds',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='kambi_odds',
        ),
    ]
